import {
  Agent,
  Market,
  Position,
  Trade,
  Wallet,
  Portfolio,
  DashboardData,
} from './types';

export const mockWallet: Wallet = {
  id: 'wallet-1',
  address: '0x742d35Cc6634C0532925a3b844Bc4e7595f42bE2',
  balance: 125000,
  available: 85000,
  reserved: 40000,
  usdc_balance: 542.50,
};

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Bull Market Scout',
    description: 'Long-biased strategy targeting emerging prediction markets',
    status: 'active',
    owner: 'You',
    createdAt: '2024-01-15',
    updatedAt: '2024-04-07',
    configuration: {
      strategyType: 'Long Bias',
      riskLevel: 'medium',
      maxPositionSize: 10000,
      maxLeverage: 2,
      stopLossPercentage: 5,
      takeProfitPercentage: 15,
      rebalanceFrequency: 'weekly',
    },
    performance: {
      totalTrades: 145,
      winRate: 0.62,
      profitLoss: 18500,
      roi: 0.148,
      sharpeRatio: 1.85,
      maxDrawdown: 0.12,
    },
  },
  {
    id: 'agent-2',
    name: 'Volatility Harvester',
    description: 'Neutral strategy exploiting short-term price swings',
    status: 'active',
    owner: 'You',
    createdAt: '2024-02-20',
    updatedAt: '2024-04-07',
    configuration: {
      strategyType: 'Market Neutral',
      riskLevel: 'low',
      maxPositionSize: 5000,
      maxLeverage: 1,
      stopLossPercentage: 3,
      takeProfitPercentage: 8,
      rebalanceFrequency: 'daily',
    },
    performance: {
      totalTrades: 287,
      winRate: 0.55,
      profitLoss: 12300,
      roi: 0.123,
      sharpeRatio: 2.1,
      maxDrawdown: 0.08,
    },
  },
  {
    id: 'agent-3',
    name: 'Political Events Trader',
    description: 'Focused on election and geopolitical outcomes',
    status: 'paused',
    owner: 'You',
    createdAt: '2024-03-10',
    updatedAt: '2024-04-05',
    configuration: {
      strategyType: 'Event-Driven',
      riskLevel: 'high',
      maxPositionSize: 15000,
      maxLeverage: 3,
      stopLossPercentage: 8,
      takeProfitPercentage: 20,
      rebalanceFrequency: 'as-needed',
    },
    performance: {
      totalTrades: 52,
      winRate: 0.71,
      profitLoss: 28500,
      roi: 0.285,
      sharpeRatio: 1.45,
      maxDrawdown: 0.18,
    },
  },
];

export const mockMarkets: Market[] = [
  {
    id: 'market-1',
    title: 'Will the Fed cut rates in 2024?',
    description: 'Predicts whether the Federal Reserve will cut interest rates in 2024',
    venue: 'Polymarket',
    category: 'Economics',
    liquidityPool: 450000,
    volume24h: 125000,
    impliedProbability: 0.72,
    endDate: '2024-12-31',
    createdAt: '2024-01-05',
    status: 'open',
    outcomes: [
      {
        id: 'outcome-1-1',
        name: 'Yes',
        probability: 0.72,
        oddsFractional: '5/2',
        oddsDecimal: 2.5,
      },
      {
        id: 'outcome-1-2',
        name: 'No',
        probability: 0.28,
        oddsFractional: '12/5',
        oddsDecimal: 3.4,
      },
    ],
  },
  {
    id: 'market-2',
    title: 'Will Bitcoin reach $100k by EOY 2024?',
    description: 'Predicts whether Bitcoin will reach a price of $100,000 by end of 2024',
    venue: 'Polymarket',
    category: 'Crypto',
    liquidityPool: 650000,
    volume24h: 320000,
    impliedProbability: 0.45,
    endDate: '2024-12-31',
    createdAt: '2024-02-01',
    status: 'open',
    outcomes: [
      {
        id: 'outcome-2-1',
        name: 'Yes',
        probability: 0.45,
        oddsFractional: '11/9',
        oddsDecimal: 2.22,
      },
      {
        id: 'outcome-2-2',
        name: 'No',
        probability: 0.55,
        oddsFractional: '9/11',
        oddsDecimal: 1.82,
      },
    ],
  },
  {
    id: 'market-3',
    title: 'Will AI regulation pass Congress in 2024?',
    description: 'Predicts if comprehensive AI regulation will be passed by Congress',
    venue: 'Manifold',
    category: 'Politics',
    liquidityPool: 320000,
    volume24h: 87000,
    impliedProbability: 0.35,
    endDate: '2024-12-31',
    createdAt: '2024-03-15',
    status: 'open',
    outcomes: [
      {
        id: 'outcome-3-1',
        name: 'Yes',
        probability: 0.35,
        oddsFractional: '13/10',
        oddsDecimal: 2.3,
      },
      {
        id: 'outcome-3-2',
        name: 'No',
        probability: 0.65,
        oddsFractional: '10/13',
        oddsDecimal: 1.77,
      },
    ],
  },
  {
    id: 'market-4',
    title: 'Will US unemployment stay below 4.5% through 2024?',
    description: 'Predicts if US unemployment rate will remain below 4.5% for all of 2024',
    venue: 'Kalshi',
    category: 'Economics',
    liquidityPool: 280000,
    volume24h: 95000,
    impliedProbability: 0.62,
    endDate: '2024-12-31',
    createdAt: '2024-02-10',
    status: 'open',
    outcomes: [
      {
        id: 'outcome-4-1',
        name: 'Yes',
        probability: 0.62,
        oddsFractional: '8/5',
        oddsDecimal: 2.6,
      },
      {
        id: 'outcome-4-2',
        name: 'No',
        probability: 0.38,
        oddsFractional: '5/8',
        oddsDecimal: 1.63,
      },
    ],
  },
];

export const mockPositions: Position[] = [
  {
    id: 'pos-1',
    marketId: 'market-1',
    agentId: 'agent-1',
    outcomeId: 'outcome-1-1',
    quantity: 50,
    entryPrice: 0.68,
    currentPrice: 0.72,
    unrealizedPnL: 2,
    percentage: 5.88,
    createdAt: '2024-03-20',
    status: 'open',
  },
  {
    id: 'pos-2',
    marketId: 'market-2',
    agentId: 'agent-1',
    outcomeId: 'outcome-2-1',
    quantity: 75,
    entryPrice: 0.42,
    currentPrice: 0.45,
    unrealizedPnL: 2.25,
    percentage: 7.14,
    createdAt: '2024-03-25',
    status: 'open',
  },
  {
    id: 'pos-3',
    marketId: 'market-3',
    agentId: 'agent-2',
    outcomeId: 'outcome-3-2',
    quantity: 100,
    entryPrice: 0.65,
    currentPrice: 0.65,
    unrealizedPnL: 0,
    percentage: 0,
    createdAt: '2024-04-01',
    status: 'open',
  },
  {
    id: 'pos-4',
    marketId: 'market-4',
    agentId: 'agent-2',
    outcomeId: 'outcome-4-1',
    quantity: 120,
    entryPrice: 0.60,
    currentPrice: 0.62,
    unrealizedPnL: 2.4,
    percentage: 3.33,
    createdAt: '2024-03-28',
    status: 'open',
  },
];

export const mockTrades: Trade[] = [
  {
    id: 'trade-1',
    marketId: 'market-1',
    agentId: 'agent-1',
    type: 'buy',
    price: 0.68,
    quantity: 50,
    total: 34,
    fee: 0.34,
    timestamp: '2024-03-20T14:22:00Z',
    status: 'completed',
  },
  {
    id: 'trade-2',
    marketId: 'market-2',
    agentId: 'agent-1',
    type: 'buy',
    price: 0.42,
    quantity: 75,
    total: 31.5,
    fee: 0.31,
    timestamp: '2024-03-25T09:15:00Z',
    status: 'completed',
  },
  {
    id: 'trade-3',
    marketId: 'market-1',
    agentId: 'agent-2',
    type: 'sell',
    price: 0.71,
    quantity: 40,
    total: 28.4,
    fee: 0.28,
    timestamp: '2024-04-02T16:45:00Z',
    status: 'completed',
  },
  {
    id: 'trade-4',
    marketId: 'market-3',
    agentId: 'agent-2',
    type: 'buy',
    price: 0.65,
    quantity: 100,
    total: 65,
    fee: 0.65,
    timestamp: '2024-04-01T11:30:00Z',
    status: 'completed',
  },
  {
    id: 'trade-5',
    marketId: 'market-4',
    agentId: 'agent-2',
    type: 'buy',
    price: 0.60,
    quantity: 120,
    total: 72,
    fee: 0.72,
    timestamp: '2024-03-28T13:20:00Z',
    status: 'completed',
  },
];

export const mockPortfolio: Portfolio = {
  totalValue: 125000,
  availableBalance: 85000,
  positions: mockPositions,
  trades: mockTrades,
  agents: mockAgents,
  wallet: mockWallet,
};

export const mockDashboardData: DashboardData = {
  portfolio: mockPortfolio,
  recentTrades: mockTrades.slice(0, 3),
  topPerformers: mockAgents.slice(0, 2),
  marketAlerts: [
    {
      id: 'alert-1',
      marketId: 'market-2',
      type: 'movement',
      message: 'Bitcoin market probability moved 5% in 1 hour',
      timestamp: '2024-04-07T10:30:00Z',
    },
    {
      id: 'alert-2',
      marketId: 'market-1',
      type: 'liquidity',
      message: 'Fed rates market liquidity increased by 50%',
      timestamp: '2024-04-07T09:15:00Z',
    },
  ],
};
